debezium/debezium-connector-informix

.github/workflows/cross-maven.yml, .github/workflows/maven.yml, pom.xml, src/main/java/io/debezium/connector/informix/InformixConnection.java, src/main/java/io/debezium/connector/informix/InformixConnectorConfig.java, src/main/java/io/debezium/connector/informix/InformixEventMetadataProvider.java, src/main/java/io/debezium/connector/informix/InformixOffsetContext.java, src/main/java/io/debezium/connector/informix/InformixSourceInfoStructMaker.java, src/main/java/io/debezium/connector/informix/SourceInfo.java, src/test/docker/informix-cdc-docker/12/Dockerfile, src/test/docker/informix-cdc-docker/14/Dockerfile, src/test/java/io/debezium/connector/informix/SourceInfoTest.java, src/test/java/io/debezium/connector/informix/util/TestHelper.java
* Fixing current_timestamp for Informix 12.10
* Tuning ifx cdc parameters
* Fixing workflows
=> DBZ-7137 Fixing current_timestamp for Informix 12.10

src/main/java/io/debezium/connector/informix/InformixConnectorTask.java, src/test/java/io/debezium/connector/informix/InformixReselectColumnsProcessorIT.java
https://issues.redhat.com/browse/DBZ-4321
Sibling PR from main repository https://github.com/debezium/debezium/pull/5081
=> DBZ-4321 Add `PostProcessor` support

src/main/java/io/debezium/connector/informix/InformixChangeEventSourceFactory.java, src/main/java/io/debezium/connector/informix/InformixConnectorTask.java, src/main/java/io/debezium/connector/informix/InformixSnapshotChangeEventSource.java
https://issues.redhat.com/browse/DBZ-7301
=> DBZ-7301 Inject the SnapshotterService

pom.xml, src/main/java/io/debezium/connector/informix/InformixDatabaseSchema.java, src/main/java/io/debezium/connector/informix/InformixDefaultValueConverter.java, src/main/java/io/debezium/connector/informix/InformixValueConverters.java, src/test/docker/informix-cdc-docker/12/Dockerfile, src/test/docker/informix-cdc-docker/14/Dockerfile, src/test/java/io/debezium/connector/informix/AbstractInformixDefaultValueIT.java, src/test/java/io/debezium/connector/informix/InformixOfflineDefaultValueIT.java
https://issues.redhat.com/browse/DBZ-7372
=> DBZ-7372 Fix default values

src/test/java/io/debezium/connector/informix/SourceInfoTest.java
https://issues.redhat.com/browse/DBZ-7107
Requires - https://github.com/debezium/debezium/pull/5261
=> DBZ-7107 Add micro/nano second based timestamps to source info block

.github/workflows/cross-maven.yml, .github/workflows/maven.yml, pom.xml
Use ti to disable flaky tests on GH CI.
=> [ci] Add flaky test env. variable

src/main/java/io/debezium/connector/informix/InformixConnection.java, src/main/java/io/debezium/connector/informix/InformixStreamingChangeEventSource.java, src/test/java/io/debezium/connector/informix/InformixConnectorIT.java, src/test/java/io/debezium/connector/informix/util/TestHelper.java
https://issues.redhat.com/browse/DBZ-7531
=> DBZ-7531 Connector Not Detecting Changses after Restart

src/main/java/io/debezium/connector/informix/InformixConnectorConfig.java, src/main/java/io/debezium/connector/informix/InformixConnectorTask.java, src/main/java/io/debezium/connector/informix/InformixStreamingChangeEventSource.java
related to: https://github.com/debezium/debezium/pull/5401
=> DBZ-7308 Adapt to core changes

src/main/java/io/debezium/connector/informix/InformixConnection.java, src/main/java/io/debezium/connector/informix/InformixConnectorConfig.java, src/main/java/io/debezium/connector/informix/InformixConnectorTask.java, src/main/java/io/debezium/connector/informix/InformixSnapshotChangeEventSource.java, src/main/java/io/debezium/connector/informix/Lsn.java, src/main/java/io/debezium/connector/informix/snapshot/lock/ExclusiveSnapshotLock.java, src/main/java/io/debezium/connector/informix/snapshot/lock/ShareSnapshotLock.java, src/main/java/io/debezium/connector/informix/snapshot/query/SelectAllSnapshotQuery.java, src/main/resources/META-INF/services/io.debezium.snapshot.spi.SnapshotLock, src/main/resources/META-INF/services/io.debezium.snapshot.spi.SnapshotQuery, src/test/java/io/debezium/connector/informix/CustomTestSnapshot.java, src/test/java/io/debezium/connector/informix/IncrementalSnapshotIT.java, src/test/java/io/debezium/connector/informix/InformixCdcTypesIT.java, src/test/java/io/debezium/connector/informix/InformixConnectorIT.java, src/test/java/io/debezium/connector/informix/InformixValidateColumnOrderIT.java, src/test/resources/META-INF/services/io.debezium.snapshot.spi.SnapshotQuery, src/test/resources/META-INF/services/io.debezium.spi.snapshot.Snapshotter
closes: https://issues.redhat.com/browse/DBZ-7699
=> DBZ-7699 Align snapshot modes

src/main/java/io/debezium/connector/informix/InformixConnection.java, src/main/java/io/debezium/connector/informix/InformixConnectorTask.java
related to: https://github.com/debezium/debezium/pull/5436
=> DBZ-7717 LogPositionValidator is no more needed in InformixConnection

src/main/java/io/debezium/connector/informix/snapshot/lock/ExclusiveSnapshotLock.java, src/main/java/io/debezium/connector/informix/snapshot/lock/ShareSnapshotLock.java, src/main/java/io/debezium/connector/informix/snapshot/query/SelectAllSnapshotQuery.java
related to: https://github.com/debezium/debezium/pull/5460
=> DBZ-7732 Add connector specific annotation to SnapshotLock and SnapshotQuery implementations

.github/workflows/cross-maven.yml
Rework GitHub Action to reuse cache-key from build step during matrix jobs.
=> [ci] Rework build step and caching

src/main/java/io/debezium/connector/informix/InformixConnection.java
related to: https://github.com/debezium/debezium/pull/5473
=> DBZ-7765 Add Partition parameter to validateLogPosition

src/test/java/io/debezium/connector/informix/AbstractInformixDefaultValueIT.java, src/test/java/io/debezium/connector/informix/BlockingSnapshotIT.java, src/test/java/io/debezium/connector/informix/InformixCdcTypesIT.java, src/test/java/io/debezium/connector/informix/InformixConnectorIT.java, src/test/java/io/debezium/connector/informix/InformixValidateColumnOrderIT.java, src/test/java/io/debezium/connector/informix/SchemaHistoryTopicIT.java, src/test/java/io/debezium/connector/informix/TransactionMetadataIT.java
Improving integration tests. This PR should adress the flowing JIRAs:
DBZ-7539
DBZ-7540
DBZ-7542
DBZ-7543
DBZ-7556
=> [ci] improving integration tests (back-port)

src/main/java/io/debezium/connector/informix/InformixConnectorConfig.java, src/main/java/io/debezium/connector/informix/InformixConnectorTask.java
related to: https://github.com/debezium/debezium/pull/5483
=> DBZ-7616 Add query timeout property

src/test/java/io/debezium/connector/informix/NotificationsIT.java
related to: https://github.com/debezium/debezium/pull/5559
=> DBZ-7858 Align NotificationsIT test to core changes

src/main/java/io/debezium/connector/informix/InformixTaskContext.java
relates to: https://github.com/debezium/debezium/pull/5718
=> DBZ-8035 Align core changes

src/main/java/io/debezium/connector/informix/InformixOffsetContext.java, src/main/java/io/debezium/connector/informix/InformixSnapshotChangeEventSource.java, src/main/java/io/debezium/connector/informix/InformixStreamingChangeEventSource.java, src/test/java/io/debezium/connector/informix/InformixConnectorIT.java, src/test/java/io/debezium/connector/informix/SchemaHistoryTopicIT.java
related to: https://github.com/debezium/debezium/pull/5938 that must be merged first
=> DBZ-7903 Improve blocking snapshot reliability in case of restart

src/test/java/io/debezium/connector/informix/SourceInfoTest.java
Depends on https://github.com/debezium/debezium/pull/6037
=> DBZ-8499 Make source info versioned

src/main/java/io/debezium/connector/informix/InformixConnectorTask.java
related to: https://github.com/debezium/debezium/pull/6430
=> DBZ-9020 Align to core changes

.github/workflows/cross-maven.yml, src/test/java/io/debezium/connector/informix/BlockingSnapshotIT.java, src/test/java/io/debezium/connector/informix/IncrementalSnapshotIT.java, src/test/java/io/debezium/connector/informix/InformixConnectorIT.java, src/test/java/io/debezium/connector/informix/InformixOfflineDefaultValueIT.java, src/test/java/io/debezium/connector/informix/util/TestHelper.java
Fix forceful shutdown of change event source coordinator (tests)
Depends on debezium/debezium#6516
=> DBZ-9154 Fix forceful shutdown of change event source coordinator

src/main/java/io/debezium/connector/informix/InformixConnection.java, src/main/java/io/debezium/connector/informix/InformixSnapshotChangeEventSource.java, src/main/java/io/debezium/connector/informix/InformixStreamingChangeEventSource.java
This pull request complements https://github.com/debezium/debezium/pull/6521.
=> DBZ-9169: Override JdbcConnection#quoteIdentifier() instead of quotedColumnIdString()

.github/workflows/cross-maven.yml, .github/workflows/maven.yml, README.md, src/main/java/io/debezium/connector/informix/InformixCdcTransactionEngine.java, src/main/java/io/debezium/connector/informix/InformixChangeTable.java, src/main/java/io/debezium/connector/informix/InformixConnection.java, src/main/java/io/debezium/connector/informix/InformixConnectorTask.java, src/main/java/io/debezium/connector/informix/InformixDatabaseSchema.java, src/main/java/io/debezium/connector/informix/InformixIdentifierQuoter.java, src/main/java/io/debezium/connector/informix/InformixPartition.java, src/main/java/io/debezium/connector/informix/InformixSnapshotChangeEventSource.java, src/main/java/io/debezium/connector/informix/InformixStreamingChangeEventSource.java, src/test/java/io/debezium/connector/informix/AbstractInformixDefaultValueIT.java, src/test/java/io/debezium/connector/informix/BlockingSnapshotIT.java, src/test/java/io/debezium/connector/informix/IncrementalSnapshotIT.java, src/test/java/io/debezium/connector/informix/InformixConnectorIT.java, src/test/java/io/debezium/connector/informix/InformixDelimitedIdentifiersIT.java, src/test/java/io/debezium/connector/informix/InformixOfflineDefaultValueIT.java, src/test/java/io/debezium/connector/informix/InformixValidateColumnOrderIT.java, src/test/java/io/debezium/connector/informix/util/TestHelper.java
Backlporting support for Informix Delimited Identifiers
=> DBZ-8773 - Support for Informix Delimited Identifiers (backport)

pom.xml, src/test/java/io/debezium/connector/informix/util/TestHelper.java
requires: https://github.com/debezium/debezium/pull/6496
=> DBZ-9110 Align core changes

src/main/java/io/debezium/connector/informix/InformixConnectorTask.java, src/test/java/io/debezium/connector/informix/InformixErrorHandlerTest.java
Refer to https://github.com/debezium/debezium/pull/6468 for additional details.
=> DBZ-8968: Add support for pluggable ArrayDeque

src/main/java/io/debezium/connector/informix/InformixConnectorTask.java
closes: https://issues.redhat.com/browse/DBZ-9377
#depends on https://github.com/debezium/debezium/pull/6671
=> DBZ-9377 Migrate External Connectors to ScheduledHeartbeat
